version: '3'
services:
  what-do-you-say-blue-server:
    image: what-do-you-say-blue-server:latest
    container_name: what-do-you-say-blue-server
    volumes:
      - /home/ubuntu/deploy/what-do-you-say-server:/deploy/what-do-you-say-server
    ports:
      - '9002:9002'
    environment:
      NODE_ENV: production
      PORT: 9002
      TZ: Asia/Seoul
    tty: true
