version: '3'
services:
  what-do-you-say-green-server:
    image: what-do-you-say-single-server:latest
    container_name: what-do-you-say-green-server
    volumes:
      - /home/ubuntu/deploy/what-do-you-say-server:/deploy/what-do-you-say-server
    ports:
      - '9003:9003'
    environment:
      NODE_ENV: production
      PORT: 9003
      TZ: Asia/Seoul
    tty: true
