version: '3'
services:
  what-do-you-say-server-blue:
    image: what-do-you-say-server-blue:latest
    container_name: what-do-you-say-server-blue
    volumes:
      - ./dist:/home/node/api/dist
      - ./src:/home/node/api/src
      - ./package.json:/home/node/api/package.json
      - ./.env:/home/node/api/.env
      - ./.env.sample:/home/node/api/.env.sample
      - ./.babelrc:/home/node/api/.babelrc
      - ./.eslintrc:/home/node/api/.eslintrc
    ports:
      - '9002:9002'
    environment:
      NODE_ENV: production
      PORT: 9002
      TZ: Asia/Seoul
    tty: true
